kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
spec:
  selector:
    hw2-swe645-0.0.1-SNAPSHOT: tomcat
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
